package com.lai.entity.generator;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Mobile_Phone
     *
     * @mbg.generated
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Sex
     *
     * @mbg.generated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Weixin
     *
     * @mbg.generated
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.QQ
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Enterprise_Name
     *
     * @mbg.generated
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Contact_Name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Contact_Phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Real_Name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Nick_Name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID_Card_Num
     *
     * @mbg.generated
     */
    private String idCardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Office_Phone
     *
     * @mbg.generated
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.License
     *
     * @mbg.generated
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Qualification
     *
     * @mbg.generated
     */
    private String qualification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Other_File
     *
     * @mbg.generated
     */
    private String otherFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.City
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Enable
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User_Type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IsPay
     *
     * @mbg.generated
     */
    private Boolean ispay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IsApprove
     *
     * @mbg.generated
     */
    private Boolean isapprove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Payment_Password
     *
     * @mbg.generated
     */
    private String paymentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Pay_Date
     *
     * @mbg.generated
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Store_ID
     *
     * @mbg.generated
     */
    private String storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.contact_address
     *
     * @mbg.generated
     */
    private String contactAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Other_File1
     *
     * @mbg.generated
     */
    private String otherFile1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Other_File2
     *
     * @mbg.generated
     */
    private String otherFile2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_Time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Member_Valid_Untill
     *
     * @mbg.generated
     */
    private Date memberValidUntill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Enable_Valid_Untill
     *
     * @mbg.generated
     */
    private Date enableValidUntill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Person_Veri_Flg
     *
     * @mbg.generated
     */
    private String personVeriFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Company_Veri_Flg
     *
     * @mbg.generated
     */
    private String companyVeriFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.View_Project_Count
     *
     * @mbg.generated
     */
    private Short viewProjectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.View_Team_Count
     *
     * @mbg.generated
     */
    private Short viewTeamCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.View_Resume_Count
     *
     * @mbg.generated
     */
    private Short viewResumeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Membership_Attribute
     *
     * @mbg.generated
     */
    private String membershipAttribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Device
     *
     * @mbg.generated
     */
    private String device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LastLoginTime
     *
     * @mbg.generated
     */
    private String lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Is_Push
     *
     * @mbg.generated
     */
    private String isPush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LastActiveTime
     *
     * @mbg.generated
     */
    private String lastactivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weChatPath
     *
     * @mbg.generated
     */
    private String wechatpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.total_Consumption
     *
     * @mbg.generated
     */
    private BigDecimal totalConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_Buy_Superpack
     *
     * @mbg.generated
     */
    private String isBuySuperpack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_Zt_Flag
     *
     * @mbg.generated
     */
    private String isZtFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Code
     *
     * @return the value of user.Code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Code
     *
     * @param code the value for user.Code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Account
     *
     * @return the value of user.Account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Account
     *
     * @param account the value for user.Account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Mobile_Phone
     *
     * @return the value of user.Mobile_Phone
     *
     * @mbg.generated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Mobile_Phone
     *
     * @param mobilePhone the value for user.Mobile_Phone
     *
     * @mbg.generated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Email
     *
     * @return the value of user.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Email
     *
     * @param email the value for user.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Address
     *
     * @return the value of user.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Address
     *
     * @param address the value for user.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Sex
     *
     * @return the value of user.Sex
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Sex
     *
     * @param sex the value for user.Sex
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Weixin
     *
     * @return the value of user.Weixin
     *
     * @mbg.generated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Weixin
     *
     * @param weixin the value for user.Weixin
     *
     * @mbg.generated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.QQ
     *
     * @return the value of user.QQ
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.QQ
     *
     * @param qq the value for user.QQ
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Enterprise_Name
     *
     * @return the value of user.Enterprise_Name
     *
     * @mbg.generated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Enterprise_Name
     *
     * @param enterpriseName the value for user.Enterprise_Name
     *
     * @mbg.generated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Contact_Name
     *
     * @return the value of user.Contact_Name
     *
     * @mbg.generated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Contact_Name
     *
     * @param contactName the value for user.Contact_Name
     *
     * @mbg.generated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Contact_Phone
     *
     * @return the value of user.Contact_Phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Contact_Phone
     *
     * @param contactPhone the value for user.Contact_Phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Real_Name
     *
     * @return the value of user.Real_Name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Real_Name
     *
     * @param realName the value for user.Real_Name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Nick_Name
     *
     * @return the value of user.Nick_Name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Nick_Name
     *
     * @param nickName the value for user.Nick_Name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID_Card_Num
     *
     * @return the value of user.ID_Card_Num
     *
     * @mbg.generated
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID_Card_Num
     *
     * @param idCardNum the value for user.ID_Card_Num
     *
     * @mbg.generated
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Office_Phone
     *
     * @return the value of user.Office_Phone
     *
     * @mbg.generated
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Office_Phone
     *
     * @param officePhone the value for user.Office_Phone
     *
     * @mbg.generated
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Fax
     *
     * @return the value of user.Fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Fax
     *
     * @param fax the value for user.Fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.License
     *
     * @return the value of user.License
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.License
     *
     * @param license the value for user.License
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Qualification
     *
     * @return the value of user.Qualification
     *
     * @mbg.generated
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Qualification
     *
     * @param qualification the value for user.Qualification
     *
     * @mbg.generated
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Other_File
     *
     * @return the value of user.Other_File
     *
     * @mbg.generated
     */
    public String getOtherFile() {
        return otherFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Other_File
     *
     * @param otherFile the value for user.Other_File
     *
     * @mbg.generated
     */
    public void setOtherFile(String otherFile) {
        this.otherFile = otherFile == null ? null : otherFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Province
     *
     * @return the value of user.Province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Province
     *
     * @param province the value for user.Province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.City
     *
     * @return the value of user.City
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.City
     *
     * @param city the value for user.City
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Region
     *
     * @return the value of user.Region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Region
     *
     * @param region the value for user.Region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Enable
     *
     * @return the value of user.Enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Enable
     *
     * @param enable the value for user.Enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.User_Type
     *
     * @return the value of user.User_Type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.User_Type
     *
     * @param userType the value for user.User_Type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IsPay
     *
     * @return the value of user.IsPay
     *
     * @mbg.generated
     */
    public Boolean getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IsPay
     *
     * @param ispay the value for user.IsPay
     *
     * @mbg.generated
     */
    public void setIspay(Boolean ispay) {
        this.ispay = ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IsApprove
     *
     * @return the value of user.IsApprove
     *
     * @mbg.generated
     */
    public Boolean getIsapprove() {
        return isapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IsApprove
     *
     * @param isapprove the value for user.IsApprove
     *
     * @mbg.generated
     */
    public void setIsapprove(Boolean isapprove) {
        this.isapprove = isapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Avatar
     *
     * @return the value of user.Avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Avatar
     *
     * @param avatar the value for user.Avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Payment_Password
     *
     * @return the value of user.Payment_Password
     *
     * @mbg.generated
     */
    public String getPaymentPassword() {
        return paymentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Payment_Password
     *
     * @param paymentPassword the value for user.Payment_Password
     *
     * @mbg.generated
     */
    public void setPaymentPassword(String paymentPassword) {
        this.paymentPassword = paymentPassword == null ? null : paymentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Pay_Date
     *
     * @return the value of user.Pay_Date
     *
     * @mbg.generated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Pay_Date
     *
     * @param payDate the value for user.Pay_Date
     *
     * @mbg.generated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Store_ID
     *
     * @return the value of user.Store_ID
     *
     * @mbg.generated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Store_ID
     *
     * @param storeId the value for user.Store_ID
     *
     * @mbg.generated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.contact_address
     *
     * @return the value of user.contact_address
     *
     * @mbg.generated
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.contact_address
     *
     * @param contactAddress the value for user.contact_address
     *
     * @mbg.generated
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Other_File1
     *
     * @return the value of user.Other_File1
     *
     * @mbg.generated
     */
    public String getOtherFile1() {
        return otherFile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Other_File1
     *
     * @param otherFile1 the value for user.Other_File1
     *
     * @mbg.generated
     */
    public void setOtherFile1(String otherFile1) {
        this.otherFile1 = otherFile1 == null ? null : otherFile1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Other_File2
     *
     * @return the value of user.Other_File2
     *
     * @mbg.generated
     */
    public String getOtherFile2() {
        return otherFile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Other_File2
     *
     * @param otherFile2 the value for user.Other_File2
     *
     * @mbg.generated
     */
    public void setOtherFile2(String otherFile2) {
        this.otherFile2 = otherFile2 == null ? null : otherFile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_Time
     *
     * @return the value of user.Create_Time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_Time
     *
     * @param createTime the value for user.Create_Time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Member_Valid_Untill
     *
     * @return the value of user.Member_Valid_Untill
     *
     * @mbg.generated
     */
    public Date getMemberValidUntill() {
        return memberValidUntill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Member_Valid_Untill
     *
     * @param memberValidUntill the value for user.Member_Valid_Untill
     *
     * @mbg.generated
     */
    public void setMemberValidUntill(Date memberValidUntill) {
        this.memberValidUntill = memberValidUntill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Enable_Valid_Untill
     *
     * @return the value of user.Enable_Valid_Untill
     *
     * @mbg.generated
     */
    public Date getEnableValidUntill() {
        return enableValidUntill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Enable_Valid_Untill
     *
     * @param enableValidUntill the value for user.Enable_Valid_Untill
     *
     * @mbg.generated
     */
    public void setEnableValidUntill(Date enableValidUntill) {
        this.enableValidUntill = enableValidUntill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Person_Veri_Flg
     *
     * @return the value of user.Person_Veri_Flg
     *
     * @mbg.generated
     */
    public String getPersonVeriFlg() {
        return personVeriFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Person_Veri_Flg
     *
     * @param personVeriFlg the value for user.Person_Veri_Flg
     *
     * @mbg.generated
     */
    public void setPersonVeriFlg(String personVeriFlg) {
        this.personVeriFlg = personVeriFlg == null ? null : personVeriFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Company_Veri_Flg
     *
     * @return the value of user.Company_Veri_Flg
     *
     * @mbg.generated
     */
    public String getCompanyVeriFlg() {
        return companyVeriFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Company_Veri_Flg
     *
     * @param companyVeriFlg the value for user.Company_Veri_Flg
     *
     * @mbg.generated
     */
    public void setCompanyVeriFlg(String companyVeriFlg) {
        this.companyVeriFlg = companyVeriFlg == null ? null : companyVeriFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.View_Project_Count
     *
     * @return the value of user.View_Project_Count
     *
     * @mbg.generated
     */
    public Short getViewProjectCount() {
        return viewProjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.View_Project_Count
     *
     * @param viewProjectCount the value for user.View_Project_Count
     *
     * @mbg.generated
     */
    public void setViewProjectCount(Short viewProjectCount) {
        this.viewProjectCount = viewProjectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.View_Team_Count
     *
     * @return the value of user.View_Team_Count
     *
     * @mbg.generated
     */
    public Short getViewTeamCount() {
        return viewTeamCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.View_Team_Count
     *
     * @param viewTeamCount the value for user.View_Team_Count
     *
     * @mbg.generated
     */
    public void setViewTeamCount(Short viewTeamCount) {
        this.viewTeamCount = viewTeamCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.View_Resume_Count
     *
     * @return the value of user.View_Resume_Count
     *
     * @mbg.generated
     */
    public Short getViewResumeCount() {
        return viewResumeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.View_Resume_Count
     *
     * @param viewResumeCount the value for user.View_Resume_Count
     *
     * @mbg.generated
     */
    public void setViewResumeCount(Short viewResumeCount) {
        this.viewResumeCount = viewResumeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Membership_Attribute
     *
     * @return the value of user.Membership_Attribute
     *
     * @mbg.generated
     */
    public String getMembershipAttribute() {
        return membershipAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Membership_Attribute
     *
     * @param membershipAttribute the value for user.Membership_Attribute
     *
     * @mbg.generated
     */
    public void setMembershipAttribute(String membershipAttribute) {
        this.membershipAttribute = membershipAttribute == null ? null : membershipAttribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Device
     *
     * @return the value of user.Device
     *
     * @mbg.generated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Device
     *
     * @param device the value for user.Device
     *
     * @mbg.generated
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LastLoginTime
     *
     * @return the value of user.LastLoginTime
     *
     * @mbg.generated
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LastLoginTime
     *
     * @param lastlogintime the value for user.LastLoginTime
     *
     * @mbg.generated
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime == null ? null : lastlogintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Is_Push
     *
     * @return the value of user.Is_Push
     *
     * @mbg.generated
     */
    public String getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Is_Push
     *
     * @param isPush the value for user.Is_Push
     *
     * @mbg.generated
     */
    public void setIsPush(String isPush) {
        this.isPush = isPush == null ? null : isPush.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LastActiveTime
     *
     * @return the value of user.LastActiveTime
     *
     * @mbg.generated
     */
    public String getLastactivetime() {
        return lastactivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LastActiveTime
     *
     * @param lastactivetime the value for user.LastActiveTime
     *
     * @mbg.generated
     */
    public void setLastactivetime(String lastactivetime) {
        this.lastactivetime = lastactivetime == null ? null : lastactivetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weChatPath
     *
     * @return the value of user.weChatPath
     *
     * @mbg.generated
     */
    public String getWechatpath() {
        return wechatpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weChatPath
     *
     * @param wechatpath the value for user.weChatPath
     *
     * @mbg.generated
     */
    public void setWechatpath(String wechatpath) {
        this.wechatpath = wechatpath == null ? null : wechatpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.total_Consumption
     *
     * @return the value of user.total_Consumption
     *
     * @mbg.generated
     */
    public BigDecimal getTotalConsumption() {
        return totalConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.total_Consumption
     *
     * @param totalConsumption the value for user.total_Consumption
     *
     * @mbg.generated
     */
    public void setTotalConsumption(BigDecimal totalConsumption) {
        this.totalConsumption = totalConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_Buy_Superpack
     *
     * @return the value of user.is_Buy_Superpack
     *
     * @mbg.generated
     */
    public String getIsBuySuperpack() {
        return isBuySuperpack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_Buy_Superpack
     *
     * @param isBuySuperpack the value for user.is_Buy_Superpack
     *
     * @mbg.generated
     */
    public void setIsBuySuperpack(String isBuySuperpack) {
        this.isBuySuperpack = isBuySuperpack == null ? null : isBuySuperpack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_Zt_Flag
     *
     * @return the value of user.is_Zt_Flag
     *
     * @mbg.generated
     */
    public String getIsZtFlag() {
        return isZtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_Zt_Flag
     *
     * @param isZtFlag the value for user.is_Zt_Flag
     *
     * @mbg.generated
     */
    public void setIsZtFlag(String isZtFlag) {
        this.isZtFlag = isZtFlag == null ? null : isZtFlag.trim();
    }
}