# ================ spring 配置
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/51-music?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
#    username: root
#    password: 123456
    url: jdbc:mysql://47.111.71.133/:3306/51-music?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    username: root
    password: w2570078967
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: file:${static.web.images-path},file:${static.web.packages-path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
  servlet:
    context-path: /51-music
  # http://localhost:8083/51-music/swagger-ui.html


# httpClient 广东警务云大数据接口
gdjwy:
  base_url: https://68.26.19.197:8343/v1/apigw/oauth2/token
  client_id: 0fdf2ebc09544cc082136ed85a1413da
  client_secret: 9a5863bc1ad64c2999f2628fb5cebd28
  grant_type: client_credentials


# =============== 联动ip和启动项目的资源静态资源(spring-resource)-自动去查找静态路径里面的资源
datasource:
  basePath: http://192.168.40.59:8081/springboot-test01/


# ================ 静态文件资源路径
static:
  web:
    packages-path: /Users/laixueshi/applicationApp/webstorm/person/springboot-test/packages/
    images-path: /Users/laixueshi/applicationFile/file/person/springboot-test/images/
    file-path: /Users/laixueshi/applicationFile/file/person/springboot-test/file/
    video-path: /Users/laixueshi/applicationFile/file/person/springboot-test/video/


# ================= 网易云接口
wangyiyun-music:
    # base-path: http://47.111.71.133:3000
    # music-song: https://music.163.com/song/media/outer/url?id=${id}.mp3


# ================= mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lai.entity
  # 以下配置均有默认值,可以不设置
  global-config:
    # 关闭MP3.0+自带的banner
    banner: false
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: auto
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      # 驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，默认为 1）x
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，默认为 0）
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
    jdbc-type-for-null: 'null'